TOKENS = {
    "bitcoin": "BTC",
    "dogecoin": "DOGE",
    "baby-doge-coin": "BABYDOGE",
    "terra-luna": "LUNA",
    "shiba-inu": "SHIB",
    "ripple": "XRP",
    "dogs-2":"DOGS",
    "x-empire":"X Empire",
    "aura-on-sol":"Aura",
    "tron":"Tron",
    "pi-network":"PI",
    "aptos":"Aptos",
    "stupidcoin-2":"STUPID",
    "jupiter-exchange-solana":"JUPITER",
    "shiba-inu":"Shiba",
    "solana":"Solana",
    "the-open-network":"Ton",
    "pudgy-penguins":"Pudgy Penguins",
    "polkadot":"Polkadot",
    "sonic-3":"SONIC",
    "stellar":"Stellar",
    "polygon-ecosystem-token":"PLYGON",
    "official-trump":"TRUMP",
    "baby-doge-coin":"Baby-Doge",
    "pancakeswap-token":"CAKE",
    "solayer":"Layer",
    "xen-crypto":"Xen",
    "pepe":"PEPE",
    "pax-gold":"PAXG",
    "cardano":"CARDANO",
    "sui":"SUI",
    "monero":"MONERO",
    "uniswap":"UNISWAP",
    "crypto-com-chain":"Cronos",
    "render-token":"RENDER",
    "filecoin":"FILECOIN",
    "bonk":"BONK",
    "sonic-3":"SONIC",
    "floki":"FLOKI",
    "notcoin":"NOT",
    "lambo-4":"LAMBO",
    "hosico-cat":"HOSICO CAT",
    "book-of-ai-meow":"BOAM",
    "sahara-ai":"SAHARA-AI",
    "chill-guy":"CHILL GUY",
    "official-trump":"TRUMP",
    "ethereum":"Ethereum",
    "hyperliquid":"HyperLiquid",
    "chainlink":"Chain Link",
    "avalanche-2":"Avalanche",
    "aave":"Aave",
    "optimism":"Optimism",
    "gooncoin":"GOONC",
    "plume":"PLUME",
    "gatechain-token":"Gate",
    "polygon-ecosystem-token":"Matic",
    "flock-2":"Flock",
    "notcoin":"Not",
    "gram-2":"Gram",
    "sei-network":"SEI",
    "story-2":"IP",
    "based-brett":"BRETT",
    "livepeer":"LPT",
    "peanut-the-squirrel":"PNUT",
    "ai16z":"AI16z",
    "injective-protocol":"INJ",
    "supah":"SUPAH",
    "huma-finance":"HUMA",
    "bone-shibaswap":"Bone-Shiba",
    "flock-2":"Flock",
    "rune-pups":"PUPS",
    "pooh":"POOH",
    "assisterr-ai":"ASSi-AI",
    "agentfun-ai":"AGENTFun",
    "book-of-meme":"BOOK-OF-MEME",
    "fitcoin-3":"FITCoin",
    "zuzalu-inu":"Zuzalu",
    "kava": "Kava",
    "assisterr-ai":"ASRR",
    "aspecta":"ASP",
    "lagrange":"LAGRANGE",
    "trusta-ai":"TRUSTA-AI",
    "polyhedra-network":"ZKJ",
    "magic":"Magic",
    "myx-finance":"MYX",
    "troll-2":"Troll",
    "conflux-token":"CFX",
    "woo-network":"WOO",
    "soon-2":"Soon"
}
